#!/bin/bash

#check if this is a directory

if !git rev-parse --is-inside-work-tree &> /dev/null; then
	echo "This is not a Git repository."
	exit 1
       fi

#Staging changes

git add .

#ASk for commit message and Branch name

read -p "What's the commit this time: " commit_message
read -p "what's the branch: " branch_name
#commiting

git commit -m "$commit_message"

#push to github
git push origin $branch_name

